PSTS6/Models/MainModels/Project.cs
using PSTS6.Models.IdentityModels;
using PSTS6.Models.MainModels;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace PSTS6.Models
{
    public class Project : MainEntity
    {


        public IEnumerable<Task> Tasks { get; set; }
        public string ProjectManager { get; set; }
        public ICollection<ProjectUser> ProjectUsers { get; set; }
        public bool Completed
        {
            get
            {
                if (PrcCompleted == 100)
                {
                    return true;
                }

                else
                {
                    return false;
                }
            }
            set { }


        }
        [DisplayName("Percentage Completed")]
        public override int PrcCompleted
        {
            get;set;
        }
        [DataType(DataType.Currency)]
        [Column(TypeName = "decimal(18,2)")]
        public override decimal Budget
        {
            get;set;
        }

    }
}

PSTS6/Controllers/ProjectUserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Primitives;
using PSTS6.Data;
using PSTS6.Models;
using PSTS6.Models.MainModels;
using PSTS6.Models.ViewModels;

namespace PSTS6.Controllers
{
    public class ProjectUserController : Controller

        
    {
        private readonly PSTS6Context _context;

        public ProjectUserController(PSTS6Context context)
        {
            _context = context;
        }

        // GET: ProjectTeam
        public ActionResult Index()
        {
            return View();
        }

        // GET: ProjectTeam/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: ProjectTeam/Create
        public ActionResult Create(string btnAddTeam)
        {
            var project = _context.Project.Where(x => x.ID == Convert.ToInt32(btnAddTeam)).FirstOrDefault();

            var users = _context.Users.AsEnumerable();

            var existingProjectMembers = _context.ProjectUsers.Where(x=>x.ProjectID== Convert.ToInt32(btnAddTeam)).ToList();

            var selectedUsers = from user in users
                                join prjUser in existingProjectMembers on user.Id equals prjUser.UserID
                                where prjUser.ProjectID == project.ID
                                select user;

            var notSelectedUsers = from user in users                           
                                   where !(selectedUsers.Contains(user))
                                   select user;


            var viewModel = new ProjectUserCreateViewModel
            {
                Project = project,
                ProjectID = project.ID,
                SelectedUsers = selectedUsers,
                NotSelectedUsers = notSelectedUsers
            };




            return View(viewModel);
        }

        // POST: ProjectTeam/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(string btnAdd, IEnumerable<string> list)
        {
            try
            {
                int projectid = Convert.ToInt32(btnAdd);

                var projectUsers = _context.ProjectUsers.Where(x=>x.ProjectID==projectid).ToList();

                _context.RemoveRange(projectUsers);
                _context.SaveChanges();

                projectUsers.Clear();


                List<ProjectUser> newList = new List<ProjectUser>();


                foreach (var item in list)
                {
                    var projectUser = new ProjectUser
                    {
                        ProjectID = projectid,
                        UserID = _context.Users.Where(z => z.UserName == item).Select(x => x.Id).FirstOrDefault()
                    };

                    projectUsers.Add(projectUser);

                }

                _context.AddRange(projectUsers);

                _context.SaveChanges();


                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: ProjectTeam/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: ProjectTeam/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: ProjectTeam/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: ProjectTeam/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

PSTS6/Controllers/TasksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using PSTS6.Data;
using PSTS6.Models;
using PSTS6.Repository;

namespace PSTS6.Controllers
{
    [Authorize]
    public class TasksController : Controller
    {       
        private readonly IMapper _mapper;
        private readonly IRepository _repo;

        public TasksController(IMapper mapper, IRepository repo)
        {          
            _mapper = mapper;
            _repo = repo;
        }

        // GET: Tasks
        public async Task<IActionResult> Index()
        {        
            return View(await _repo.GetTasksAsync());
        }

        // GET: Tasks/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var task = await _repo.GetTask(id);

            if (task == null)
            {
                return NotFound();
            }

            return View(task);
        }

    
        public async Task<IActionResult> Create(string btnAddTask)
        {
            var dbUsers = await _repo.GetUsersAsync();

            IEnumerable<SelectListItem> users = dbUsers.Select(x => new SelectListItem
            {
                Text = x.UserName,
                Value = x.UserName
                
            });

            var projects = await _repo.GetProjectsAsync(filter:false);

            IEnumerable<SelectListItem> projectsToSelect = projects.Select(x => new SelectListItem
            {
                Text = x.Name,
                Value = x.ID.ToString(),
                        
            });

            var viewModel = new TaskCreateViewModel
            {
                availableOwners = users,
                StartDate = DateTime.Today,
                EstimatedEndDate = DateTime.Today,

                availableProjects = projectsToSelect.Where(x => x.Value == btnAddTask)
            };

            return View(viewModel);
        }

        // POST: Tasks/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("StartDate,EstimatedEndDate,ID,Name,Description,ProjectID")] PSTS6.Models.Task task)
        {
            if (ModelState.IsValid)
            {

                string selectedProject = Request.Form["Project"].ToString();

                task.ProjectID = Convert.ToInt32(selectedProject);

                await _repo.AddTask(task);
                
                return RedirectToAction("Edit","Projects", new { id= task.ProjectID});
            }
            return View(task);
        }

        // GET: Tasks/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var task = await _repo.GetTask(id);

            var viewModel = _mapper.Map<TaskEditViewModel>(task);

            if (task == null)
            {
                return NotFound();
            }
            return View(viewModel);
        }

        // POST: Tasks/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("PrcCompleted,Budget,StartDate,EstimatedEndDate,ActualEndDate,Spent,ID,Name,Description,ProjectID")] PSTS6.Models.Task task)
        {
            if (id != task.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await _repo.UpdateTask(task);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TaskExists(task.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Edit", "Projects", new { id = task.ProjectID });
            }
            return View(task);
        }

        // GET: Tasks/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var task = await _repo.GetTask(id);
            if (task == null)
            {
                return NotFound();
            }

            return View(task);
        }

        // POST: Tasks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var task = await _repo.GetTask(id);

            var projectid = task.ProjectID;

            await _repo.DeleteTask(task);

            return RedirectToAction("Edit", "Projects", new { id = projectid });
        }

        private bool TaskExists(int id)
        {
            return _repo.TaskExists(id);
        }
    }
}

PSTS6/Views/Projects/Create.cshtml
@model PSTS6.Models.ProjectCreateViewModel

@{
    ViewData["Title"] = "Create";
   
}

<h1>Create</h1>

<h4>Project</h4>
<hr />

<div class="row">

   
    <div class="col-md-4">
        
        <form asp-action="Create">
            <div class="form-check">
                <label>Create from Template</label>
                <input type="checkbox" name="createFromTemplate" id="checkbox" />
            </div>
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <h5>Create Manually</h5>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="StartDate" class="control-label"></label>
                <input asp-for="StartDate" class="form-control" />
                <span asp-validation-for="StartDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EstimatedEndDate" class="control-label"></label>
                <input asp-for="EstimatedEndDate" class="form-control" />
                <span asp-validation-for="EstimatedEndDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                @Html.LabelFor(x => Model.ProjectManager, new { @class = "control-label" })
                @Html.DropDownListFor(x => Model.ProjectManager, new SelectList(Model.availableProjectManagers, "Value", "Text")
               , new { @class = "form-control" })
                <span asp-validation-for="ProjectManager" class="text-danger"></span>
            </div>




            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
            <div class="col-md-4">
                <h5>Create From Template</h5>
                <div class="form-group">

                    <label>Select Template</label>
                    @Html.DropDownListFor(x => Model.Template, new SelectList(Model.Templates, "Value", "Text")
                   , new { @class = "form-control" })
                    <span asp-validation-for="Template" class="text-danger"></span>
                </div>
            </div>
        </form>
    </div>
   
        
    


</div>


<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

PSTS6/Views/Projects/Delete.cshtml
@model PSTS6.Models.Project

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Project</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Completed)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Completed)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PrcCompleted)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PrcCompleted)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Budget)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Budget)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StartDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EstimatedEndDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EstimatedEndDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ActualEndDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ActualEndDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Spent)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Spent)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

PSTS6/Views/Projects/Details.cshtml
@model PSTS6.Models.Project

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<partial name="Gantt" />

PSTS6/Views/Projects/Edit.cshtml
@model ProjectEditViewModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>
<div class="row">
    <div class="col-md-4">
        <h4>Project</h4>
    </div>
    <div class="col-md-4">
        <h4>Items</h4>
    </div>

</div>
        
        <hr />
        <div class="row">
            <div class="col-md-4">
                <form asp-action="Edit">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <input type="hidden" asp-for="ID" />
                    <div class="form-group">
                        <label asp-for="Name" class="control-label"></label>
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Description" class="control-label"></label>
                        <input asp-for="Description" class="form-control" />
                        <span asp-validation-for="Description" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="StartDate" class="control-label"></label>
                        <input asp-for="StartDate" class="form-control" />
                        <span asp-validation-for="StartDate" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="EstimatedEndDate" class="control-label"></label>
                        <input asp-for="EstimatedEndDate" class="form-control" />
                        <span asp-validation-for="EstimatedEndDate" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="ActualEndDate" class="control-label"></label>
                        <input asp-for="ActualEndDate" class="form-control" />
                        <span asp-validation-for="ActualEndDate" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        @if (Model.ActualEndDateSetting == "1")
                        {
                            @Html.LabelFor(x => Model.ProjectManager, new { @class = "control-label" })
                            @Html.DropDownListFor(x => Model.ProjectManager, new SelectList(Model.AvailableProjectManagers, "Value", "Text", Model.ProjectManager)
                           , new { @class = "form-control" })
                        }
                        else
                        {
                            @Html.LabelFor(x => Model.ProjectManager, new { @class = "control-label" })
                            @Html.DropDownListFor(x => Model.ProjectManager, new SelectList(Model.AvailableProjectManagers, "Value", "Text", Model.ProjectManager)
                           , new { @class = "form-control", @readonly="readonly" })
                        }



                        <span asp-validation-for="ProjectManager" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <input type="submit" value="Save" class="btn btn-primary" />
                    </div>
                    <div>
                        <button class="btn btn-dark" name="btnAddTask" value="@Model.ID" formmethod="get" asp-area="" asp-controller="Tasks" asp-action="Create">Add a new task</button>
                        <button class="btn btn-dark" name="btnAddTeam" value="@Model.ID" formmethod="get" asp-area="" asp-controller="ProjectUser" asp-action="Create">Edit Project Team</button>
                    </div>
                </form>
                <div>
                    <a asp-action="Index">Back to List</a>
                </div>
            </div>

            <div class="col-md-8">

                <partial name="/Views/Shared/_TasksList.cshtml" />
            </div>

        </div>
        <div class="row">
            <div class="col-md-5">
                <h3>Project Team</h3>
                <table class="table">
                    <thead class="thead-dark">
                        <tr>
                            <th scope="col">
                                UserName
                            </th>
                            <th scope="col">
                                Email
                            </th>

                        </tr>

                    </thead>
                    <tbody>
                        @foreach (var item in Model.ProjectTeam)
                        {
                            <tr>

                                <td>@Html.DisplayFor(modelItem => item.UserName)</td>
                                <td>@Html.DisplayFor(modelItem => item.Email)</td>
                                

                            </tr>
                        }
                        </tbody>

                </table>
            </div>
        </div>
        


        @section Scripts {
            @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
        }

PSTS6/Views/Projects/Index.cshtml
@model IEnumerable<PSTS6.Models.Project>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            
            <th>
                @Html.DisplayNameFor(model => model.ProjectManager)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PrcCompleted)
            </th>

            <th>
                @Html.DisplayNameFor(model => model.StartDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EstimatedEndDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ActualEndDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Budget)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Spent)
            </th>


            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
           
            <td>
                @Html.DisplayFor(modelItem => item.ProjectManager)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PrcCompleted)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.StartDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EstimatedEndDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ActualEndDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Budget)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Spent)
            </td>


            <td>
                <a asp-action="Edit" asp-route-id="@item.ID">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.ID">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.ID">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>