PSTS6/Models/ViewModels/ManagerDashboardViewModel.cs
using Microsoft.AspNetCore.Identity;
using ReflectionIT.Mvc.Paging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PSTS6.Models
{
    public class ManagerDashboardViewModel
    {
        public PagingList<Project> PendingProjects { get; set; }

        public PagingList<Project> OverBudgetProjects { get; set; }

        public PagingList<Project> FinishedProjects { get; set; }

      
    }
}

PSTS6/Models/ViewModels/UserDashboardViewModel.cs
using Microsoft.AspNetCore.Identity;
using ReflectionIT.Mvc.Paging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PSTS6.Models
{
    public class UserDashboardViewModel
    {

        public PagingList<Activity> PendingActivities { get; set; }

        public PagingList<Activity> OverBudgetActivities { get; set; }

        public PagingList<Activity> PlannedActivities { get; set; }

        public PagingList<Activity> FinishedActivities { get; set; }

       







    }
}

PSTS6/Controllers/ActivitiesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PSTS6.Data;
using PSTS6.Models;
using PSTS6.HelperClasses;
using PSTS6.Repository;

namespace PSTS6.Controllers
{
    [Authorize]
    public class ActivitiesController : Controller
    {
        private readonly PSTS6Context _context;
        private readonly IRepository _repo;
        private readonly IMapper _mapper;
       
        public ActivitiesController(PSTS6Context context, IMapper mapper, IRepository repo)
        {
            _context = context;
            _mapper = mapper;
            
            _repo = repo;
        }

        // GET: Activities
        public async Task<IActionResult> Index()
        {
            return View(await _repo.GetActivitiesAsync(filterByUser:false));
        }

        // GET: Activities/Details/5
        [Authorize(Policy = "OwnerRolePolicy")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var activity = await _repo.GetActivityAsync(id);
            if (activity == null)
            {
                return NotFound();
            }

            return View(activity);
        }

        // GET: Activities/Create
        public IActionResult Create(string btnAddActivity)
        {

            var viewModel = new ActivityCreateViewModel
            {
                TaskID = Convert.ToInt32(btnAddActivity),
                StartDate = DateTime.Today,
                EstimatedEndDate = DateTime.Today
            };
            return View(viewModel);
        }

        // POST: Activities/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("PrcCompleted,Budget,StartDate,EstimatedEndDate,ActualEndDate,Spent,ID,Name,Description,TaskID")] Activity activity)
        {
            if (ModelState.IsValid)
            {
                await _repo.AddActivityAsync(activity);
                return RedirectToAction("Edit", "Tasks", new { id = activity.TaskID });
            }
            return View(activity);
        }

        // GET: Activities/Edit/5
        [Authorize(Policy = "EditDetailsActivityPolicy")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var activity = await _repo.GetActivityAndLoadRelatedDataAsync(id.GetValueOrDefault());
          
            var project = activity.Task.Project;
        
            var users = await _repo.GetUsersAsync();

            var projectUsers = await _repo.GetProjectUsers();

            var projectTeam= from user in users
                             join prjUser in projectUsers on user.Id equals prjUser.UserID
                             where prjUser.ProjectID == project.ID
                             select user;


            IEnumerable<SelectListItem> owners = projectTeam.Select(x => new SelectListItem
            {
                Text = x.UserName,
                Value = x.UserName
            });

            var viewModel = _mapper.Map<ActivityEditViewModel>(activity);
            viewModel.AvailableOwners=owners;

            viewModel.Owner = activity.Owner;


            if (activity == null)
            {
                return NotFound();
            }
            return View(viewModel);
        }

        // POST: Activities/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Policy = "EditDetailsActivityPolicy")]
        public async Task<IActionResult> Edit(int id, [Bind("PrcCompleted,Budget,StartDate,EstimatedEndDate,ActualEndDate,Spent,ID,Name,Description,TaskID,Owner")] Activity activity)
        {
            if (id != activity.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await _repo.UpdateActivityAsync(activity);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ActivityExists(activity.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Edit", "Tasks", new { id = activity.TaskID });
            }
            return View(activity);
        }

        // GET: Activities/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var activity = await _repo.GetActivityAsync(id);
            if (activity == null)
            {
                return NotFound();
            }

            return View(activity);
        }

        // POST: Activities/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var activity = await _repo.GetActivityAsync(id);
            await _repo.DeleteActivityAsync(activity);
            return RedirectToAction(nameof(Index));
        }

        private bool ActivityExists(int id)
        {
            return _repo.ActivityExists(id);
        }
    }
}

PSTS6/Controllers/TasksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using PSTS6.Data;
using PSTS6.Models;
using PSTS6.Repository;

namespace PSTS6.Controllers
{
    [Authorize]
    public class TasksController : Controller
    {       
        private readonly IMapper _mapper;
        private readonly IRepository _repo;

        public TasksController(IMapper mapper, IRepository repo)
        {          
            _mapper = mapper;
            _repo = repo;
        }

        // GET: Tasks
        public async Task<IActionResult> Index()
        {        
            return View(await _repo.GetTasksAsync());
        }

        // GET: Tasks/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var task = await _repo.GetTask(id);

            if (task == null)
            {
                return NotFound();
            }

            return View(task);
        }

    
        public async Task<IActionResult> Create(string btnAddTask)
        {
            var dbUsers = await _repo.GetUsersAsync();

            IEnumerable<SelectListItem> users = dbUsers.Select(x => new SelectListItem
            {
                Text = x.UserName,
                Value = x.UserName
                
            });

            var projects = await _repo.GetProjectsAsync(filter:false);

            IEnumerable<SelectListItem> projectsToSelect = projects.Select(x => new SelectListItem
            {
                Text = x.Name,
                Value = x.ID.ToString(),
                        
            });

            var viewModel = new TaskCreateViewModel
            {
                availableOwners = users,
                StartDate = DateTime.Today,
                EstimatedEndDate = DateTime.Today,

                availableProjects = projectsToSelect.Where(x => x.Value == btnAddTask)
            };

            return View(viewModel);
        }

        // POST: Tasks/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("StartDate,EstimatedEndDate,ID,Name,Description,ProjectID")] PSTS6.Models.Task task)
        {
            if (ModelState.IsValid)
            {

                string selectedProject = Request.Form["Project"].ToString();

                task.ProjectID = Convert.ToInt32(selectedProject);

                await _repo.AddTask(task);
                
                return RedirectToAction("Edit","Projects", new { id= task.ProjectID});
            }
            return View(task);
        }

        // GET: Tasks/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var task = await _repo.GetTask(id);

            var viewModel = _mapper.Map<TaskEditViewModel>(task);

            if (task == null)
            {
                return NotFound();
            }
            return View(viewModel);
        }

        // POST: Tasks/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("PrcCompleted,Budget,StartDate,EstimatedEndDate,ActualEndDate,Spent,ID,Name,Description,ProjectID")] PSTS6.Models.Task task)
        {
            if (id != task.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await _repo.UpdateTask(task);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TaskExists(task.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Edit", "Projects", new { id = task.ProjectID });
            }
            return View(task);
        }

        // GET: Tasks/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var task = await _repo.GetTask(id);
            if (task == null)
            {
                return NotFound();
            }

            return View(task);
        }

        // POST: Tasks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var task = await _repo.GetTask(id);

            var projectid = task.ProjectID;

            await _repo.DeleteTask(task);

            return RedirectToAction("Edit", "Projects", new { id = projectid });
        }

        private bool TaskExists(int id)
        {
            return _repo.TaskExists(id);
        }
    }
}

PSTS6/Controllers/UserController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PSTS6.Data;
using PSTS6.Models;
using PSTS6.Models.IdentityModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PSTS6.Controllers
{
    public class UserController : Controller
    {
        private readonly PSTS6Context _context;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;

        public UserController(PSTS6Context context, UserManager<IdentityUser> userManager, RoleManager<IdentityRole> roleManager)
        {
            _context = context;
            _userManager = userManager;
            _roleManager = roleManager;
        }

        public async Task<IActionResult> Index()
        {

           

            return View(await _context.Users.ToListAsync());
        }

        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.Users.Where(x => x.Id == id).FirstOrDefaultAsync();

          
           

            var userRole = await _context.UserRoles.Where(x => x.UserId == id).FirstOrDefaultAsync();

            var roles = await _context.Roles.ToListAsync();

            var role = roles.Where(x => x.Id == userRole.RoleId).FirstOrDefault();

            var selectedRole = role.Name;

            IEnumerable<SelectListItem> rolesSelectList = roles.Select(x => new SelectListItem
            {
                Text = x.Name,
                Value = x.Name,


            });

            foreach (var item in rolesSelectList)
            {
                if (item.Text.Equals(role.Name))
                {
                    item.Selected = true;
                }
               
            }

            var viewModel = new UserEditViewModel
            {
                UserName = user.UserName,
                Email = user.Email,
                AvailableRoles = rolesSelectList,
                SelectedRole = selectedRole
            };

            

            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("UserName,Email,Id,PasswordHash,EmailConfirmed,LockoutEnabled")] IdentityUser user)
        {

            if (id != user.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {

                    user = _context.Users.Where(x => x.Id == user.Id).FirstOrDefault();

                    string selectedRole = Request.Form["SelectedRole"].ToString();

                    user.UserName = Request.Form["UserName"].ToString();

                    user.Email = Request.Form["Email"].ToString();

                    List<IdentityUserRole<string>> userRoles = _context.UserRoles.Where(x => x.UserId == user.Id).ToList();

                    foreach (var item in userRoles)
                    {
                        _context.Remove(item);
                    }

                   await _userManager.AddToRoleAsync(user, selectedRole);
                   
                    _context.Update(user);

                   await _context.SaveChangesAsync();

                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UserExists(user.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View();
        }
        private bool UserExists(string id)
        {
            return _context.Users.Any(e => e.Id == id);
        }

    }

   

}

PSTS6/Views/Shared/AdminDashboard.cshtml
@model PSTS6.Models.CommonDashboardViewModel
<h2>This is Admin Dashboard</h2>

<partial name="/Views/Shared/UserDashboard.cshtml"     />
<partial name="/Views/Shared/ManagerDashboard.cshtml" />

PSTS6/Views/Shared/Gantt.cshtml
<head>
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
    <script type="text/javascript">
        google.charts.load('current', { 'packages': ['gantt'] });
        google.charts.setOnLoadCallback(drawChart);

        function daysToMilliseconds(days) {
            return days * 24 * 60 * 60 * 1000;
        }

        function drawChart() {


            var value = window.location.href;

            var secondValue = value.substring(value.lastIndexOf('/') + 1)

            var url = "https://localhost:44335/api/" + secondValue;

            var jsonData = $.ajax({
                url: url,
                dataType: "text",
                async: false
            }).responseText;




            //The returned string must be parsed as JSON
            var array = JSON.parse(jsonData);

            //
            //transform the JSON to JavaScript DataTable
            var datatabledata = new google.visualization.arrayToDataTable(array);



            //Optional options for the Chart. See  https://developers.google.com/chart/interactive/docs/gallery/ganttchart for more options
            var options = {
                height: 1000,
                gantt: {
                    arrow: {
                        angle: 60,
                        width: 1,
                        color: '#ffe0b200',
                    },
                    criticalPathEnabled: false
                }
            };

            //Create a new Chart object
            var chart = new google.visualization.Gantt(document.getElementById('chart_div'));

            //Draw the chart
            chart.draw(datatabledata, options);
        }
    </script>


</head>

<body>
    <div id="chart_div"></div>
</body>

PSTS6/Views/Shared/_ActivitiesList.cshtml
@model TaskEditViewModel


<table class="table">
    <thead class="thead-light">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                % Completed
            </th>
            <th>
                Budget
            </th>
            <th>
                Start Date
            </th>
            <th>
                Estimated End Date
            </th>
            <th></th>
            

            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.Activities) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PrcCompleted)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Budget)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.StartDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EstimatedEndDate)
            </td>
            
            
            <td>
                <input type="button" class="btn-sm btn-primary" title="Open" value="Open" onclick="location.href='@Url.Action("Edit","Activities", new {id=item.ID})'" />

            
            <td>
                <input type="button" class="btn-sm btn-danger" title="Delete" value="Delete" onclick="location.href='@Url.Action("Delete","Activities", new {id=item.ID})'" />
            </td>
            
        </tr>
}
    </tbody>
</table>

PSTS6/Views/Shared/_ActivityTemplatesList.cshtml
@model PSTS6.Models.TaskTemplateViewModel


<table class="table">
    <thead>
        <tr>

            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Budget)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.ActivityTemplates) {
        <tr>

            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Budget)
            </td>
            <td>
                <input type="button" class="btn-sm btn-primary" title="Open" value="Open"
                       onclick="location.href='@Url.Action("Edit","ActivityTemplates", new {id=item.ID})'" />

            </td>
            <td>
                <input type="button" class="btn-sm btn-danger" title="Delete" value="Delete"
                       onclick="location.href='@Url.Action("Delete","ActivityTemplates", new {id=item.ID})'" />
            </td>>
        </tr>
}
    </tbody>
</table>

PSTS6/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PSTS6</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />

    <link rel="canonical" href="https://getbootstrap.com/docs/4.5/examples/dashboard/">

    <style>
          .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            -ms-user-select: none;
            user-select: none;
          }

          @*@media (min-width: 768px) {
            .bd-placeholder-img-lg {
              font-size: 3.5rem;
            }
          }*@
    </style>
    <!-- Custom styles for this template -->
    <link href="\dashboard\dashboard.css" rel="stylesheet">



</head>
<body>
    <nav class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
        <a class="navbar-brand col-md-3 col-lg-2 mr-0 px-3" href="#">PSTS6</a>
        <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-toggle="collapse" data-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        @*<input class="form-control form-control-dark w-50" id="SearchText" name="SearchText" type="text" placeholder="Search" aria-label="Search">*@

        @*<form style="width:75%;">

                <input class="form-control form-control-dark w-50" id="SearchText" name="SearchText" type="text" placeholder="Search" aria-label="Search">

                <input type="submit" value="Search" class="search-button" />

            </form>*@
        <form style="width:60%;" formmethod="get">
            <input class="form-control form-control-dark w-100" id="SearchText" name="SearchText" formaction="@Url.Action("GetData", "Search")" type="text" placeholder="Search" aria-label="Search">
            <input hidden type="submit" value="Search" formaction="@Url.Action("GetData", "Search")" />
        </form>

        <ul class="navbar-nav px-5">
            <partial name="_LoginPartial" />
        </ul>

    </nav>
    <div class="row">
        <div class="container-fluid">
            <div class="row">
                <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
                    <div class="sidebar-sticky pt-3">
                        <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
                            <span>My Work</span>

                        </h6>
                        <ul class="nav flex-column">


                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">
                                    <span data-feather="home"></span>
                                    Home
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Projects" asp-action="Index">
                                    <span data-feather="file"></span>
                                    Projects
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Dashboards" asp-action="Index">
                                    <span data-feather="file-text"></span>
                                    Dashboards
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="User" asp-action="Index">
                                    <span data-feather="users"></span>
                                    Users
                                </a>
                            </li>
                            @*<li class="nav-item">
                                    <a class="nav-link">
                                        <span data-feather="bar-chart-2"></span>
                                        Reports
                                    </a>
                                </li>*@

                        </ul>

                        <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
                            <span>Settings</span>

                        </h6>
                        <ul class="nav flex-column mb-2">
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Privacy">
                                    <span data-feather="file-text"></span>
                                    Privacy
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="ProjectTemplates" asp-action="Index">
                                    <span data-feather="file-text"></span>
                                    Templates
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#">
                                    <span data-feather="file-text"></span>
                                    Settings
                                </a>
                            </li>

                        </ul>
                    </div>
                </nav>
                <div class="container-fluid col-md-8">
                    <main role="main" class="pb-3">
                        @RenderBody()
                    </main>
                </div>

            </div>
        </div>



    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - PSTS6 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @*<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="../assets/js/vendor/jquery.slim.min.js"><\/script>')</script>*@

    <script src="https://cdnjs.cloudflare.com/ajax/libs/feather-icons/4.9.0/feather.min.js"></script>
    @*<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.3/Chart.min.js"></script>*@
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
    <script src="\dashboard\dashboard.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

PSTS6/Views/Shared/_ProjectTeamPartial.cshtml
@model PSTS6.Models.ViewModels.ProjectUserCreateViewModel

<div class="container-fluid">
    <h3>Add Members to the Project Team</h3>
    <div class="row">

        <div class="col-md-4">
            <ul id="usersList" class="list-group">
                @foreach (var item in Model.SelectedUsers)
                {
                    <li id="@item.Id" class="list-group-item" >@item.UserName</li>
                }

            </ul>
        </div>
        <div class="col-md-1  align-self-center ">

            <button id="movebtn" class="btn btn-info"> < > </button>


        </div>

        <div class="col-md-4">
            <ul id="usersList2" class="list-group">
            </ul>
        </div>

    </div>
    <hr>
    <div class="row">

        
     
    </div>
</div>
<script>
    // Add active class to the current button (highlight it)
    var header = document.getElementById("usersList");
    var listItems = header.getElementsByClassName("list-group-item");
    for (var i = 0; i < listItems.length; i++) {
        listItems[i].addEventListener("click", function () {
            var current = document.getElementsByClassName("active");
            if (current.length > 0) {
                current[0].className = current[0].className.replace(" active", "");
            }

            this.className += " active";
        });
    }
</script>
<script>

    document.addEventListener("DOMContentLoaded", function () {
        var selected = document.getElementsByClassName("active");
        var list1 = document.getElementById("usersList");
        var list2 = document.getElementById("usersList2");
        button = document.getElementById("movebtn");

        function moveItem() {
            var selected = document.getElementsByClassName("active");

            if (selected[0].parentElement == list1) {
                list2.appendChild(selected[0])
            } else {
                list1.appendChild(selected[0])
            }

        }
        button.addEventListener("click", moveItem)

    });
</script>