PSTS6/Models/ProjectTemplate.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PSTS6.Models
{
    public class ProjectTemplate
    {
    }
}

PSTS6/Models/TemplateModels/ProjectTemplate.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PSTS6.Models
{
    public class ProjectTemplate : TemplateEntity
    {
    }
}

PSTS6/Models/ViewModels/ProjectTemplateViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PSTS6.Models
{
    public class ProjectTemplateViewModel
    {

        public int ID { get; set; }
        public string Name { get; set; }

        public string Description { get; set; }

        public IEnumerable<TaskTemplate> TaskTemplates { get; set; }
    }
}

PSTS6/Controllers/ProjectTemplatesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PSTS6.Data;
using PSTS6.Models;
using PSTS6.Repository;

namespace PSTS6.Controllers
{
    [Authorize]
    public class ProjectTemplatesController : Controller
    {
        private readonly PSTS6Context _context;
        private readonly IMapper _mapper;
        private readonly IRepository _repo;

        public ProjectTemplatesController(PSTS6Context context, IMapper mapper, IRepository repo)
        {
            _context = context;
            _mapper = mapper;
            _repo = repo;
        }

        // GET: ProjectTemplates
        public async Task<IActionResult> Index()
        {
            return View(await _repo.GetProjectTemplatesAsync());
        }

        // GET: ProjectTemplates/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var projectTemplate = await _context.ProjectTemplate
                .FirstOrDefaultAsync(m => m.ID == id);
            if (projectTemplate == null)
            {
                return NotFound();
            }

            return View(projectTemplate);
        }

        // GET: ProjectTemplates/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: ProjectTemplates/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Name,Description")] ProjectTemplate projectTemplate)
        {
            if (ModelState.IsValid)
            {
                _context.Add(projectTemplate);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(projectTemplate);
        }

        // GET: ProjectTemplates/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            

            var projectTemplate = await _context.ProjectTemplate.Where(x => x.ID == id).Include(x => x.TaskTemplates).FirstOrDefaultAsync();

            var viewModel = _mapper.Map<ProjectTemplateViewModel>(projectTemplate);

            if (projectTemplate == null)
            {
                return NotFound();
            }
            return View(viewModel);
        }

        // POST: ProjectTemplates/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Name,Description")] ProjectTemplate projectTemplate)
        {
            if (id != projectTemplate.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(projectTemplate);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProjectTemplateExists(projectTemplate.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(projectTemplate);
        }

        // GET: ProjectTemplates/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var projectTemplate = await _context.ProjectTemplate
                .FirstOrDefaultAsync(m => m.ID == id);
            if (projectTemplate == null)
            {
                return NotFound();
            }

            return View(projectTemplate);
        }

        // POST: ProjectTemplates/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var projectTemplate = await _context.ProjectTemplate.FindAsync(id);
            _context.ProjectTemplate.Remove(projectTemplate);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProjectTemplateExists(int id)
        {
            return _context.ProjectTemplate.Any(e => e.ID == id);
        }
    }
}

PSTS6/Controllers/TaskTemplatesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PSTS6.Data;
using PSTS6.Models;

namespace PSTS6.Controllers
{
    public class TaskTemplatesController : Controller
    {
        private readonly PSTS6Context _context;
        private readonly IMapper _mapper;

        public TaskTemplatesController(PSTS6Context context, IMapper mapper)
        {
            _context = context;
            _mapper = mapper;
        }

        // GET: TaskTemplates
        public async Task<IActionResult> Index()
        {
            return View(await _context.TaskTemplate.ToListAsync());
        }

        // GET: TaskTemplates/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var taskTemplate = await _context.TaskTemplate
                .FirstOrDefaultAsync(m => m.ID == id);
            if (taskTemplate == null)
            {
                return NotFound();
            }

            return View(taskTemplate);
        }

        // GET: TaskTemplates/Create
        public IActionResult Create(string btnAddTaskTemplate)
        {
            var viewModel = new TaskTemplateCreateViewModel
            {
                ProjectTemplateID = Convert.ToInt32(btnAddTaskTemplate),
             
            };
            return View(viewModel);
        }

        // POST: TaskTemplates/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Name,Description,ProjectTemplateID")] TaskTemplate taskTemplate)
        {
            if (ModelState.IsValid)
            {
                _context.Add(taskTemplate);
                await _context.SaveChangesAsync();
                return RedirectToAction("Edit", "ProjectTemplates", new { id = taskTemplate.ProjectTemplateID });
            }
            return View(taskTemplate);
        }

        // GET: TaskTemplates/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var taskTemplate = await _context.TaskTemplate.Where(x => x.ID == id).Include(x => x.ActivityTemplates).FirstOrDefaultAsync();

            var viewModel = _mapper.Map<TaskTemplateViewModel>(taskTemplate);

            if (taskTemplate == null)
            {
                return NotFound();
            }
            return View(viewModel);
        }

        // POST: TaskTemplates/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Name,Description")] TaskTemplate taskTemplate)
        {
            if (id != taskTemplate.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(taskTemplate);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TaskTemplateExists(taskTemplate.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(taskTemplate);
        }

        // GET: TaskTemplates/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var taskTemplate = await _context.TaskTemplate
                .FirstOrDefaultAsync(m => m.ID == id);
            if (taskTemplate == null)
            {
                return NotFound();
            }

            return View(taskTemplate);
        }

        // POST: TaskTemplates/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var taskTemplate = await _context.TaskTemplate.FindAsync(id);
            _context.TaskTemplate.Remove(taskTemplate);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TaskTemplateExists(int id)
        {
            return _context.TaskTemplate.Any(e => e.ID == id);
        }
    }
}

PSTS6/Views/ProjectTemplates/Create.cshtml
@model PSTS6.Models.ProjectTemplate

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>ProjectTemplate</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

PSTS6/Views/ProjectTemplates/Delete.cshtml
@model PSTS6.Models.ProjectTemplate

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ProjectTemplate</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

PSTS6/Views/ProjectTemplates/Details.cshtml
@model PSTS6.Models.ProjectTemplate

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>ProjectTemplate</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

PSTS6/Views/ProjectTemplates/Edit.cshtml
@model PSTS6.Models.ProjectTemplateViewModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>ProjectTemplate</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
            <div>
                <button class="btn btn-dark" name="btnAddTaskTemplate" value="@Model.ID" formmethod="get" asp-area="" asp-controller="TaskTemplates" asp-action="Create">Add a new task</button>
            </div>
        </form>
    </div>

    <div class="col-md-8">

        <partial name="/Views/Shared/_TaskTemplatesList.cshtml" />
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

PSTS6/Views/ProjectTemplates/Index.cshtml
@model IEnumerable<PSTS6.Models.ProjectTemplate>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.ID">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.ID">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.ID">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>